name: CMake CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: cmake .
    - name: make
      run: make

  build-mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: cmake .
    - name: make
      run: make

#  build-win:
#
#    runs-on: windows-latest
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: configure
#      run: cmake -G "NMake Makefiles" .
#    - name: make
#      run: nmake
